---
abstract: 'Interface to myaffiliates.com API'
author:
  - 'Binary.com <fayland@binary.com>'
build_requires:
  Test::Exception: 0
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.5, Dist::Zilla version 5.014, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-MyAffiliates
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Mojo::UserAgent: 0
  XML::Simple: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/binary-com/perl-WebService-MyAffiliates/issues
  homepage: https://github.com/binary-com/perl-WebService-MyAffiliates
  repository: https://github.com/binary-com/perl-WebService-MyAffiliates.git
version: 0.01
x_contributors:
  - 'Jean-Yves Sireau <jy@binary.com>'
